In [1]:
import numpy as np
a=np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [2]:
print(a[0])

10


In [3]:
print(a[-1])

40


In [4]:
print(a.dtype)

int32


In [5]:
b=np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
c=np.arange(7,13).reshape(2,3)
c

array([[ 7,  8,  9],
       [10, 11, 12]])

In [8]:
np.concatenate((b,c))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
d=np.arange(10,100,20)
d

array([10, 30, 50, 70, 90])

In [10]:
np.array_split(d,50)

[array([10]),
 array([30]),
 array([50]),
 array([70]),
 array([90]),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 arra

In [11]:
np.where(a==30)

(array([2], dtype=int64),)

In [12]:
np.searchsorted(d,40)

2

In [13]:
np.amin(d)

10

In [14]:
np.amax(d)

90

In [15]:
np.average(d)

50.0