In [1]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [2]:
np.shape(a)

(5,)

In [6]:
b=np.array([[10,20,30],[40,50,60]])
print(b)

[[10 20 30]
 [40 50 60]]


In [7]:
np.shape(a)

(2, 3)

In [8]:
np.reshape(a,(3,2))

array([[10, 20],
       [30, 40],
       [50, 60]])

In [9]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])